name: Create HydroServer AWS Cloud Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Enter a deployment environment name.'
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  setup-deployment:
    runs-on: ubuntu-20.04
    environment: ${{ github.event.inputs.environment }}
    defaults:
      run:
        working-directory: ./terraform/aws
    steps:
      - name: configureawscredentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/${{ vars.AWS_IAM_ROLE }}
          role-session-name: create-hydroserver-resources
          aws-region: ${{ vars.AWS_REGION }}
    
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Backend
        id: backend
        run: |
          cat << EOF > backend.conf
          bucket = ${{ vars.TERRAFORM_BUCKET }}
          key=state/aws_application_${{ github.event.inputs.environment }}
          region = ${{ vars.AWS_REGION }}
          EOF

      - name: Terraform Init
        id: init
        run: terraform init -backend-config=backend.conf
  
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -backend-config=backend.conf -var instance="${{ github.event.inputs.environment }}"
        continue-on-error: true

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Terraform Apply
        run: terraform apply -auto-approve -backend-config=backend.conf -var instance="${{ github.event.inputs.environment }}"
